# Generated by Django 5.0.2 on 2024-11-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSTID', models.CharField(max_length=100)),
                ('CustomerName', models.CharField(max_length=255)),
                ('CustomerGSTIN', models.CharField(max_length=15, unique=True)),
                ('CustomerADdress', models.TextField()),
                ('CustomerPAN', models.CharField(max_length=255)),
                ('TypeofCustomer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblCreateCustomer',
            },
        ),
        migrations.CreateModel(
            name='CreateInvoiceBasedPartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=255)),
                ('VENDID', models.CharField(max_length=255)),
                ('VendorInvoiceNumber', models.CharField(max_length=255)),
                ('YearOfInvoice', models.CharField(max_length=255)),
                ('InvoicePartNumber', models.CharField(max_length=255)),
                ('BAtchID', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblCreateInvoiceBasedPartNumber',
            },
        ),
        migrations.CreateModel(
            name='CreateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=100)),
                ('CUSTID', models.CharField(max_length=255)),
                ('ProjectNAme', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('ProjCodePArtNumberSuffix', models.CharField(max_length=255)),
                ('ProjCodePartNameSuffix', models.CharField(max_length=255)),
                ('FY', models.TextField()),
            ],
            options={
                'db_table': 'tblCreateProject',
            },
        ),
        migrations.CreateModel(
            name='CreatePurchaseBasedCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=255)),
                ('COSTID', models.CharField(max_length=255)),
                ('InvoicePartNumber', models.CharField(max_length=255)),
                ('CostPerUnit', models.CharField(max_length=255)),
                ('Qty', models.CharField(max_length=255)),
                ('TotalValue', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblCreatePurchaseBasedCosting',
            },
        ),
        migrations.CreateModel(
            name='CreateVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VENDID', models.CharField(max_length=255, unique=True)),
                ('VendorNAme', models.CharField(max_length=255)),
                ('VEndorGSTIN', models.CharField(max_length=15, unique=True)),
                ('VendorAddress', models.TextField()),
                ('VendorPAN', models.CharField(blank=True, max_length=255)),
                ('TypeofVendor', models.CharField(max_length=100)),
                ('BankAcc', models.CharField(max_length=100)),
                ('IFSC', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblCreateVendor',
            },
        ),
        migrations.CreateModel(
            name='ReadPurchaseBasedCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=255)),
                ('COSTID', models.CharField(max_length=255)),
                ('TotalValue', models.CharField(max_length=255)),
                ('CostDetails', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblReadPurchaseBasedCosting',
            },
        ),
        migrations.CreateModel(
            name='UploadInvoicefromVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=255)),
                ('VENDID', models.CharField(max_length=255)),
                ('VendorInvoiceNumber', models.CharField(max_length=255)),
                ('VendorNAme', models.CharField(max_length=255)),
                ('DateofInvoice', models.CharField(max_length=255)),
                ('UnitOfMeasure', models.CharField(max_length=255)),
                ('QtyReceived', models.CharField(max_length=255)),
                ('GSTRate', models.CharField(max_length=255)),
                ('HSN', models.CharField(max_length=255)),
                ('CostPerunit', models.CharField(max_length=255)),
                ('TotalValue', models.CharField(max_length=255)),
                ('Part_number', models.CharField(blank=True, max_length=255)),
                ('Part_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'tblUploadInvoicefromVendor',
            },
        ),
        migrations.RenameField(
            model_name='tblproject',
            old_name='project_code1',
            new_name='project_code',
        ),
        migrations.RenameField(
            model_name='tblproject',
            old_name='project_name1',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='tblvendordetails',
            name='Pan_details',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblvendordetails',
            name='Tally_ledger_creation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblproject',
            name='company_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tblproject',
            name='projcode_partnumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tblvendordetails',
            name='gstin',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tblvendordetails',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='tblvendordetails',
            table=None,
        ),
    ]
