# Generated by Django 5.0.2 on 2024-11-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_createcustomer_createinvoicebasedpartnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcustomer',
            name='BankAcc',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createcustomer',
            name='Branch',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createcustomer',
            name='IFSC',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
