# Generated by Django 5.0.2 on 2024-10-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tblvendordetails_pan_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblproject',
            old_name='project_code1',
            new_name='project_code',
        ),
        migrations.RenameField(
            model_name='tblproject',
            old_name='project_name1',
            new_name='project_name',
        ),
        migrations.AlterField(
            model_name='tblproject',
            name='company_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tblproject',
            name='projcode_partnumber',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
