# Generated by Django 5.0.2 on 2024-11-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_uploadinvoicefromvendor_invoicevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadinvoicefromvendor',
            name='CGST',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadinvoicefromvendor',
            name='IGST',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadinvoicefromvendor',
            name='SGST',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
