# Generated by Django 5.0.2 on 2024-11-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tblvendordetails_gstin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VENDID', models.CharField(max_length=255, unique=True)),
                ('VendorNAme', models.CharField(max_length=255)),
                ('VEndorGSTIN', models.CharField(max_length=15, unique=True)),
                ('VendorAddress', models.TextField()),
                ('VendorPAN', models.CharField(max_length=255)),
                ('TypeofVendor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblCreateVendor',
            },
        ),
    ]
