# Generated by Django 5.0.2 on 2024-11-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_createvendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSTID', models.CharField(max_length=100)),
                ('CustomerName', models.CharField(max_length=255)),
                ('CustomerGSTIN', models.CharField(max_length=15, unique=True)),
                ('CustomerADdress', models.TextField()),
                ('CustomerPAN', models.CharField(max_length=255)),
                ('TypeofCustomer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tblCreateCustomer',
            },
        ),
    ]
