# Generated by Django 5.0.2 on 2024-11-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_uploadinvoicefromvendor_cgst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadinvoicefromvendor',
            name='OptionType',
            field=models.CharField(choices=[('LOCAL', 'LOCAL'), ('INTERSTATE', 'INTERSTATE')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
