# Generated by Django 5.0.2 on 2024-11-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_createcustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=100)),
                ('CUSTID', models.CharField(max_length=255)),
                ('ProjectNAme', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('ProjCodePArtNumberSuffix', models.CharField(max_length=255)),
                ('ProjCodePartNameSuffix', models.CharField(max_length=255)),
                ('FY', models.TextField()),
            ],
            options={
                'db_table': 'tblCreateProject',
            },
        ),
    ]
