# Generated by Django 5.0.2 on 2024-11-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_uploadinvoicefromvendor_optiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpurchasebasedcosting',
            name='CostPerUnit',
        ),
        migrations.RemoveField(
            model_name='createpurchasebasedcosting',
            name='InvoicePartNumber',
        ),
        migrations.AddField(
            model_name='createpurchasebasedcosting',
            name='InvoiceValues',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createpurchasebasedcosting',
            name='PartNames',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createpurchasebasedcosting',
            name='PartNums',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
