# Generated by Django 5.0.2 on 2024-11-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_createproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadInvoicefromVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=255)),
                ('VENDID', models.CharField(max_length=255)),
                ('VendorInvoiceNumber', models.CharField(max_length=255)),
                ('VendorNAme', models.CharField(max_length=255)),
                ('DateofInvoice', models.CharField(max_length=255)),
                ('UnitOfMeasure', models.CharField(max_length=255)),
                ('QtyReceived', models.CharField(max_length=255)),
                ('GSTRate', models.CharField(max_length=255)),
                ('HSN', models.CharField(max_length=255)),
                ('CostPerunit', models.CharField(max_length=255)),
                ('TotalValue', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblUploadInvoicefromVendor',
            },
        ),
    ]
