# Generated by Django 5.0.2 on 2024-11-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_uploadinvoicefromvendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateInvoiceBasedPartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=255)),
                ('VENDID', models.CharField(max_length=255)),
                ('VendorInvoiceNumber', models.CharField(max_length=255)),
                ('YearOfInvoice', models.CharField(max_length=255)),
                ('InvoicePartNumber', models.CharField(max_length=255)),
                ('BAtchID', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblCreateInvoiceBasedPartNumber',
            },
        ),
    ]
