# Generated by Django 5.0.2 on 2024-11-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_createinvoicebasedpartnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePurchaseBasedCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=255)),
                ('COSTID', models.CharField(max_length=255)),
                ('InvoicePartNumber', models.CharField(max_length=255)),
                ('CostPerUnit', models.CharField(max_length=255)),
                ('Qty', models.CharField(max_length=255)),
                ('TotalValue', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblCreatePurchaseBasedCosting',
            },
        ),
    ]
