# Generated by Django 5.0.2 on 2024-11-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_createpurchasebasedcosting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadPurchaseBasedCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PROJID', models.CharField(max_length=255)),
                ('COSTID', models.CharField(max_length=255)),
                ('TotalValue', models.CharField(max_length=255)),
                ('CostDetails', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblReadPurchaseBasedCosting',
            },
        ),
    ]
