# Generated by Django 5.0.2 on 2024-11-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_uploadinvoicefromvendor_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadinvoicefromvendor',
            name='Part_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
